//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agence_API.REST.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cao_usuario
    {
        public string co_usuario { get; set; }
        public string no_usuario { get; set; }
        public string ds_senha { get; set; }
        public string co_usuario_autorizacao { get; set; }
        public Nullable<long> nu_matricula { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public Nullable<System.DateTime> dt_admissao_empresa { get; set; }
        public Nullable<System.DateTime> dt_desligamento { get; set; }
        public Nullable<System.DateTime> dt_inclusao { get; set; }
        public Nullable<System.DateTime> dt_expiracao { get; set; }
        public string nu_cpf { get; set; }
        public string nu_rg { get; set; }
        public string no_orgao_emissor { get; set; }
        public string uf_orgao_emissor { get; set; }
        public string ds_endereco { get; set; }
        public string no_email { get; set; }
        public string no_email_pessoal { get; set; }
        public string nu_telefone { get; set; }
        public System.DateTime dt_alteracao { get; set; }
        public string url_foto { get; set; }
        public string instant_messenger { get; set; }
        public Nullable<int> icq { get; set; }
        public string msn { get; set; }
        public string yms { get; set; }
        public string ds_comp_end { get; set; }
        public string ds_bairro { get; set; }
        public string nu_cep { get; set; }
        public string no_cidade { get; set; }
        public string uf_cidade { get; set; }
        public Nullable<System.DateTime> dt_expedicao { get; set; }
    }
}
