//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agence_API.REST.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cao_salario
    {
        public string co_usuario { get; set; }
        public System.DateTime dt_alteracao { get; set; }
        public double brut_salario { get; set; }
        public double liq_salario { get; set; }
    }
}
