//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agence_API.REST.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cao_fatura> cao_fatura { get; set; }
        public virtual DbSet<cao_os> cao_os { get; set; }
        public virtual DbSet<cao_salario> cao_salario { get; set; }
        public virtual DbSet<cao_usuario> cao_usuario { get; set; }
        public virtual DbSet<permissao_sistema> permissao_sistema { get; set; }
    }
}
